### PR TITLE
Make PR artifacts more useful

### PR DESCRIPTION
**Pull request by tgorochowik**
Keep data about new failures, new passes and full csv files that were
used for comparison.

### CODE REVIEW

**Comment by hzeller** [comment]
Are these the ones the "compared test results" table is build from ? If so, could we embed links in the table to the artifacts that can further explain what was happening ?

**Comment by tgorochowik** [comment]
Yes, the files are the original csv files (before pr and after pr) and in addition to that, pre filtered csv files that only show new failures and new passes

**Comment by hzeller** [comment]
Nice, so could we craft URLs to this information in the generated pull request comment that contains the results table ?

**Comment by tgorochowik** [comment]
Converting to draft as adding the url requires some experimentation.

**Comment by tgorochowik** [comment]
Oh, right. We won't be able to test it here as the workflow that posts the comment has to be already on the main branch. Let me add some logs to CI that generate the link and test it there. If the URL is generated correctly, then I will add the code that appends it to the comment separately.

**Pull request merged**
