### PR TITLE
Add tree-sitter-systemverilog parser

### PR DESCRIPTION
**Pull request by gmlarumbe**

### CODE REVIEW

**Comment by tgorochowik** [comment]
Thanks for the PR, pleas rebase your PR, there have been some changes in the CI that are needed to make it pass

**Comment by tgorochowik** [comment]
Thank you for the contribution, I am glad there is some new effort towards a better SV support for tree sitter and actually wish I heard about it earlier :D great work

**Review by tgorochowik — APPROVED** [review]

**Comment by gmlarumbe** [comment]
Thanks a lot! :)

**Comment by tgorochowik** [comment]
@gmlarumbe I completely missed that you did not add a CI job for your tool, therefore it is missing in the public report. Could you please add that in a follow up PR?

**Pull request merged**
